# 4.1 Composition of poses and landmarks

## Theoretical background

The purpose of this exercise is to familiarise ourselves with the process of observing landmarks from robot poses and the transformations needed to make use of these observations.

Some concepts necessary:

- **World frame**: $x, y$ coordinates from a selected point of reference $(0, 0)$. We use to keep track of the robots pose, and within the map.
- **Observation**: Information from the real world provided by a sensor, from the point of view (*pov*) of a certain robot.
- **Range-bearing sensor**: Sensor model being used in this lesson. They detect how far is an object $(d)$ and its orientation relative to the robot's $(\theta)$.

The main tools for that are:

- the composition of two poses and the composition of a pose and a landmark.
- the propagation of uncertainty through the Jacobians of these compositions.

We will address several problems of incremental complexity. The following figures will help you to follow the exercise.

<center>
<img src="images/fig4-1-1.png" width="900">
</center>

In [ ]:
#%matplotlib notebook
%matplotlib inline

# IMPORTS

import math
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

from utils.PlotEllipse import PlotEllipse
from utils.DrawRobot import DrawRobot
from utils.tcomp import tcomp
from utils.tinv import tinv, jac_tinv1 as jac_tinv
from utils.Jacobians import J1, J2

1. Let’s consider a robot R1 at a perfectly known pose $p_1 = [1, 2, 0.5]^T$ which observes
 a landmark m with a range-bearing (polar) sensor affected by a zero-mean
 Gaussian error with covariance $W_{1p} = diag\left([0.25, 0.04]\right)$. The sensor provides the
 measurement $z_{1p} = [4m., 0.7rad.]^T$. Compute the Gaussian probability distribution
 (mean and covariance) of the landmark in the world frame (the same as the robot)
 and plot its corresponding ellipse (in magenta, $\sigma=1$).
 
 **Hint**: Prior to propagate the measurement uncertainty, we need to compute the
 covariance of the observation in the Cartesian robot R1 frame.

In [ ]:
def to_world_frame(p1_w, Qp1_w, z1_p_r, W1):
    """ Covert the observation z1_p_r to the world frame
    
        Args:
            p1_w: Pose of the robot(in world frame)
            Qp1_w: Covariance of the robot
            z1_p_r: Observation to a landmark(polar coordinates) from robots perspective
            W1: Covariance of the sensor
    
        Returns:
            z1_w: Pose of landmark in the world frame
            Qz1: Covariance associated to z1_w
    """
    # TODO: Implement function
    raise NotImplementedError
    
    return z1_w, Qz1

In [ ]:
# MATPLOTLIB
fig, ax = plt.subplots()
plt.xlim([-.5, 10])
plt.ylim([-.5, 10])
plt.grid()
plt.tight_layout()

p1_w = np.vstack([1, 2, 0.5])
Qp1_w = np.zeros((3, 3))

z1_p_r = np.vstack([4., .7])
W1 = np.diag([0.25, 0.04])

z1_w, Qz1 = to_world_frame(p1_w, Qp1_w, z1_p_r, W1)

DrawRobot(fig, ax, p1_w, label='R1', color='blue')
    
ax.plot(z1_w[0, 0], z1_w[1, 0], 'o', label='Z1', color='green')
PlotEllipse(fig, ax, z1_w, Qz1, color='green')

plt.legend()
print('----\tExercise 4.1.1\t----\n'+
      'z1_w = {}\'\n'.format(z1_w.flatten())
      + 'Wz1_w = \n{}\n'.format(Qz1))

Expected results for demo:

```
---- Exercise 4.1.1 ----
z1_w = [2.44943102 5.72815634]'
Wz1_w = 
[[ 0.58879177 -0.13171532]
 [-0.13171532  0.30120823]]
```

2. Now, let’s assume that the robot pose is not known, but a RV that follows a
Gaussian probability distribution: $p_1 \sim N([1, 2, 0.5]^T, \Sigma_1)$ with $\Sigma_1 = diag([0.08,0.6,
0.02 ])$.

    1. Compute the covariance matrix $\Sigma_{m1}$ of the landmark in the world frame and
     plot it as an ellipse centered at the mean $m_1$ (in blue, $sigma= 1$). Plot also
     the covariance of the robot pose (in blue, $sigma= 1$).
     
    2. Compare the covariance with that obtained in the previous case. Is it
     bigger? Is it bigger than that of the robot? Why?  


In [ ]:
# MATPLOTLIB
fig, ax = plt.subplots()
plt.xlim([-.5, 10])
plt.ylim([-.5, 10])
plt.grid()
plt.tight_layout()

fig.canvas.draw()

p1_w = np.vstack([1, 2, 0.5])
Qp1_w = np.𝑑𝑖𝑎𝑔([0.08,0.6,0.02])

z1_p_r = np.vstack([4., .7])
W1 = np.diag([0.25, 0.04])

z1_w, Qz1 = to_world_frame(p1_w, Qp1_w, z1_p_r, W1)

DrawRobot(fig, ax, p1_w, label='R1', color='red')  
ax.plot(z1_w[0, 0], z1_w[1, 0], 'o', label='Z1', color='green')
PlotEllipse(fig, ax, z1_w, Qz1, color='green')

plt.legend()
print('---- Exercise 4.1.2 ----\n'+
      'Wz1_w = \n{}\n'.format(Qz1))


Expected output:

```
---- Exercise 4.1.2 ----
Wz1_w = 
[[ 0.94677477 -0.23978943]
 [-0.23978943  0.94322523]]
```

3. Another robot `R2` is at pose $p_2 \sim ([6m., 4m., 2.1rad.]^T, \Sigma_2)$ with $\Sigma_2 = diag([0.20,0.09,
 0.03])$. Plot `p2` and its ellipse (covariance) in green ($sigma=1$). Compute the relative
 pose `p12` between `R1` and `R2`. For that, take a look at the file “Clarifying the
 relative pose between to poses” and implement the two possible ways to obtain
 such pose.

In [ ]:
def inverse_composition1(p1_w, Qp1_w, p2_w, Qp2_w):
    # TODO: Implement function
    raise NotImplementedError
    
    return p12_w, Qp12_w

def inverse_composition2(p1_w, Qp1_w, p2_w, Qp2_w):
    # TODO: Implement function
    raise NotImplementedError
    
    return p12_w, Qp12_w


p1_w = np.vstack([1., 2., 0.5])
Qp1_w = np.diag([0.08, 0.6, 0.02])
p2_w = np.vstack([6., 4., 2.1])
Qp2_w = np.diag([0.20, 0.09, 0.03])

p12_w, Qp12_w = inverse_composition1(p1_w, Qp1_w, p2_w, Qp2_w)
print( '----\tExercise 4.1.3 with method 1\t----\n'+
        'p12_w = {}\'\n'.format(p12_w.flatten())+
        'Qp12_w = \n{}\n'.format(Qp12_w))


p12_w, Qp12_w = inverse_composition2(p1_w, Qp1_w, p2_w, Qp2_w)
print( '----\tExercise 4.1.3 with method 2\t----\n'+
        'p12_w = {}\'\n'.format(p12_w.flatten())+
        'Qp12_w = \n{}\n'.format(Qp12_w))

Expected results:
 ```
 p12_w = [ 5.34676389 -0.64196257  1.6       ]'
 
 Qp12_w = 
 [[0.38248035 0.24115    0.01283925]
 [0.24115    1.16751965 0.10693528]
 [0.01283925 0.10693528 0.05      ]]
 ```

4. According to the information that we have about the position of the landmark m in
 the world coordinates (provided by R1), compute the *predicted observation*
 distribution of $z_{2p} =[r, \alpha] \sim N(z_{2p}, W_{2p})$ by a range-bearing sensor from `R2`.
 Hint: We need to compute the covariance of the predicted observation in Polar
 coordinates $(W_{2p})$. For that, use the following Jacobian:
 
 $$
     \frac{\partial{p}}{\partial{c}} = 
     \begin{bmatrix}
         \cos{(\alpha+\theta)}  & \sin{(\alpha+\theta)} \\
         \sin{(\alpha+\theta)} / r  & \cos{(\alpha+\theta)} / r
     \end{bmatrix}
 $$

In [ ]:
def predicted_obs_from_pov(p1_w, z1_w, Qz1_w):
    """ Method to translate a pose+covariance in the world frame to an observation.
    
        This method only translated the landmark to the pov of the robot.
        It does not simulate a new observation.
        
        Args:
            p1_w: Pose of the robot which acts as pov
            z1_w: Landmark observed in cartesian coordinates(world frame)
            Qz1_w: Covariance associated to the landmark.
        Returns:
            z2_pr: Expected observation of z1 from pov of p1_w
            W2_p: Covariance associated to z2_pr
    """

    # TODO: Implement function
    raise NotImplementedError
    
    return z2_pr, W2_p

In [ ]:
p2_w = np.vstack([6., 4., 2.1])

z2_pr, W2_p = predicted_obs_from_pov(p2_w, z1_w, Qz1)
print( '---- Exercise 4.1.4 ----\n'+
    'z2p_r = {}\'\n'.format(z2_pr.flatten())+
    'W2_p = \n{}\n'.format(W2_p)    
)

Expected output:
```
---- Exercise 4.1.4 ----
z2p_r = [3.94880545 0.58862004]'
W2_p = 
[[ 1.13481128 -0.03710981]
 [-0.03710981  0.04843106]]
```

5. Assume now that a measurement $z_2 = [4 m., 0.3 rad.]^T$ of the landmark is taken
 from R2 with a sensor having the same precision as that of R1 ($W_{2p}= W_{1p}$)
 a-b-What is the pdf of the observed landmark according to this observation?
 Plot the corresponding ellipse (in green, sigma=1).
 Two different pdf’s are now associated to the same landmark.
    1. Is that a contradiction?
    2. Can you work out a solution that combines these two “pieces of
     information”? Plot it (in red).
     
<figure style="text-align:center">
  <img src="images/fig4-1-2.png" width="400" alt="">
  <figcaption>Fig. 2: Results from the last exercise </figcaption>
</figure>    

In [ ]:
def combine_pdfs(p1_w, Qp1_w, p2_w, Qp2_w):
    # TODO: Implement function
    raise NotImplementedError
    
# MATPLOTLIB
fig, ax = plt.subplots()
plt.xlim([-.5, 10])
plt.ylim([-.5, 10])
plt.grid()
plt.tight_layout()

fig.canvas.draw()

z2_p_r = np.vstack([4., .3])
Wz2_p_r = np.diag([0.25, 0.04])

z1_w, Qz1 = to_world_frame(p1_w, Qp1_w, z1_p_r, W1)
z2_w, Qz2 = to_world_frame(p2_w, Qp2_w, z2_p_r, W1)

DrawRobot(fig, ax, p1_w, label='R1', color='blue')
PlotEllipse(fig, ax, p1_w, Qp1_w, color='blue')

DrawRobot(fig, ax, p2_w, label='R2', color='green')
PlotEllipse(fig, ax, p2_w, Qp2_w, color='green')
   
ax.plot(z1_w[0, 0], z1_w[1, 0], 'o', label='Z1', color='blue')
PlotEllipse(fig, ax, z1_w, Qz1, color='blue')
          
ax.plot(z2_w[0, 0], z2_w[1, 0], 'o', label='Z2', color='green')
PlotEllipse(fig, ax, z2_w, Qz2, color='green')

z_w, Wz_w = combine_pdfs(z1_w, Qz1, z2_w, Qz2)
ax.plot(z_w[0, 0], Wz_w[1, 0], 'o', label='Z3', color='red')
PlotEllipse(fig, ax, z_w, Wz_w, color='red')
          
plt.legend()

# Print results
print( '----\tExercise 4.1.5\t----\n'+
    'z2_w = {}\'\n'.format(z2_w.flatten())+
    'Qz2 = \n{}\n'.format(Qz2)
    )

# Print results
print( '----\tExercise 4.1.5 parte 2\t----\n'+
    'z_w = {}\'\n'.format(z_w.flatten())+
    'Wz_w = \n{}\n'.format(Wz_w)
    )

Expected ouputs:

### Sensor measurement from R2

```
z2_w = [3.05042514 6.70185272]'
Qz2 = 
[[0.84693794 0.4333316 ]
 [0.4333316  0.81306206]]
```

### Combined information
```
---- Exercise 4.1.5 parte 2 ----
z_w = [2.58757252 6.15534036]'
Wz_w = 
[[0.37966125 0.07773125]
 [0.07773125 0.36999739]]
```